services:
  web:
    build: .
    ports:
      - "5001:5001"
    depends_on:
      - db
    environment:
      FLASK_ENV: development
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: employee_db
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data: